@startuml
'https://plantuml.com/class-diagram


SimplePizzaStore -> SimplePizzaFactory
SimplePizzaFactory -> Pizza
Pizza <|-- CheesePizza
Pizza <|-- TacoPizza
Pizza <|-- PepperoniPizza

class SimplePizzaStore{
+orderPizza(String type)
}

class SimplePizzaFactory{
+createPizza(String type)
}
Abstract class Pizza {
+prepare()
+bake()
+cut()
+box()
}



@enduml