@startuml
'https://plantuml.com/class-diagram
context *--> Strategy : composed
Strategy <|-- Strategy1
Strategy <|-- Strategy2
Strategy <|-- Strategy3


class context{
+ useStrategy()
}

interface Strategy{
+doThing()
}

class Strategy1
class Strategy2
class Strategy3

@enduml