@startuml
'https://plantuml.com/class-diagram

ISubject <|-- ProductSubject

IObserver <|-- ProductObserver
ProductSubject --o ProductObserver
interface ISubject {
subscribe()
unsubscribe()
notifyObservers()
}
interface IObserver {
notify()
}

class ProductSubject{
+observerCollection
}


note "For observer in observer collection observer.notify()" as N1
N1  .. ProductSubject




@enduml